/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as appIndexRouteImport } from './pages/(app)/index'
import { Route as appDesignSystemRouteImport } from './pages/(app)/design-system'

const appIndexRoute = appIndexRouteImport.update({
  id: '/(app)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appDesignSystemRoute = appDesignSystemRouteImport.update({
  id: '/(app)/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/design-system': typeof appDesignSystemRoute
  '/': typeof appIndexRoute
}
export interface FileRoutesByTo {
  '/design-system': typeof appDesignSystemRoute
  '/': typeof appIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/design-system': typeof appDesignSystemRoute
  '/(app)/': typeof appIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/design-system' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/design-system' | '/'
  id: '__root__' | '/(app)/design-system' | '/(app)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appDesignSystemRoute: typeof appDesignSystemRoute
  appIndexRoute: typeof appIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/design-system': {
      id: '/(app)/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof appDesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  appDesignSystemRoute: appDesignSystemRoute,
  appIndexRoute: appIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
